### ISSUE TITLE
Build.PL outdated?

### ISSUE THREAD

**Issue by andk** [rizen/Ouch#10]
https://metacpan.org/source/RIZEN/Ouch-0.0409/Build.PL contains not the full set of prerequisites that is in dist.ini and Makefile.PL

Maybe an accident? This mistake leads to pleny of fail reports on cpantesters. Here is one sample:

http://www.cpantesters.org/cpan/report/50874446

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by haarg** [comment]
It seems like the dist should just not ship with the Build.PL.  If you want to keep the file in the repository but not ship with it, you should be able to exclude it by configuring the [GatherDir] plugin, or listing it in a MANIFEST.SKIP file.

**Comment by dcollinsn** [comment]
Came here to report this. Namely, users of Build.PL will see failures due to an undeclared dependency on Test::Trap.

**Comment by rizen** [comment]
removed in 0.0410
