### ISSUE TITLE
Make :trytiny more Try::Tiny-sh? [thoughts]

### ISSUE THREAD

**Issue by polettix** [rizen/Ouch#13]
Hi! Thanks for the great module, it really hits the right balance for me. I have a couple of thoughts about `:trytiny` that I would like to share.

First, binding the _enterprise-approved_ names to `:trytiny` does not make justice to Try::Tiny in my opinion. Maybe `:stickinthemud` would not be _enterprise-approved_ either, but something like `:javaesque`/`:enterprise`/`:oldfashioned` (or simply `:throw`) would have made the alternative names available without pulling Try::Tiny's sleeve.

Then, what I would really like is for `:trytiny` (or possibly something else, to avoid breaking backwards compatibility) to set the focus on `$_` instead of `$@`. Having to always pass `$_` as the optional exception parameter is somehow spoiling the fun for me.

**Comment by polettix** [comment]
I have a sample implementation of a `:trytiny_var` import option that I can propose. It's built on top of PR #14, so I'll put this in hold to avoid clobbering your input queue.

**Comment by rizen** [comment]
Thanks, I'd love to see your implementation. I've gone ahead and released your other pull request. I'm sorry for the delay.

**Comment by polettix** [comment]
Hi! I put it in #15, rebased on the current master and squashed for easier inspection.

I opted for `trytiny_var` because backwards compatibility is important IMHO. If `:trytiny` was born for the enterprise guys... so be it!

We can close this issue and continue the discussion in the PR if you vaguely like the proposal.

**Comment by rizen** [comment]
done
